[package]
name = "bevy_stl"
version = "0.3.0"
authors = ["Niklas Cathor <niklas.cathor@gmx.de>"]
edition = "2018"
license = "MIT"
description = "STL loader for bevy, based on stl_io"
repository = "https://github.com/nilclass/bevy_stl"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
stl_io = "0.5.2"
bevy_app = { git = "https://github.com/bevyengine//bevy", rev = "9d453530fac9202691c797184ad0b220b2ea37b3" }
bevy_asset = { git = "https://github.com/bevyengine//bevy", rev = "9d453530fac9202691c797184ad0b220b2ea37b3"}
bevy_render = { git = "https://github.com/bevyengine//bevy", rev = "9d453530fac9202691c797184ad0b220b2ea37b3"}
bevy_utils = { git = "https://github.com/bevyengine//bevy", rev = "9d453530fac9202691c797184ad0b220b2ea37b3" }
bevy_input = { git = "https://github.com/bevyengine//bevy", rev = "9d453530fac9202691c797184ad0b220b2ea37b3"}


[features]
default = []

# Along with the triangle mesh, generate an additional wireframe mesh (a PrimitiveTopology::LineList).
# The wireframe mesh can be accessed by `asset_server.load("my-model.stl#wireframe")`.
wireframe = []

[[example]]
name = "spinning_disc"
path = "examples/spinning_disc.rs"
